### ISSUE TITLE
Women and Men Fashions

### ISSUE THREAD

**Issue by MahmoudMH** [facg3/Elegant-Project#11]
#1 
As a user i want to see the clothes for women and men . 

**Acceptance Criteria** 

- [ ] style the page. #36 
- [ ] show the photos from database. #37
- [ ] active the button save to put the photo saved at the user account. #38
