### ISSUE TITLE
Sign up

### ISSUE THREAD

**Issue by MahmoudMH** [facg3/Elegant-Project#2]
#1 
As a user i want be registered to save what i liked at my account .
 
**Acceptance criteria**

- [x] browse sign up form fields for users details. #14
- [x] get form information and save them into the database. #16
- [x] Front End and Back End Validation. #15
- [x] Styling the page. #17
- [x] sign up oAuth. #42
