### ISSUE TITLE
Log in

### ISSUE THREAD

**Issue by MahmoudMH** [facg3/Elegant-Project#3]
#1 
As i user i have to login to show my account page and save any other outfits .

**Acceptance criteria**

- [ ] Log in form show fields for usersnames and password . #41 

- [ ]   validation #13 

- [ ] make the authentication . #18 

- [ ] Style the page . #19
