### ISSUE TITLE
Home Page

### ISSUE THREAD

**Issue by MahmoudMH** [facg3/Elegant-Project#5]
#1 
As a user i want to see the home page and navigate around the website . 

**Acceptance criteria**

- [ ] display home page with side button to navigate around the website #22
- [ ] display the header content according to user logged in or not #28
- [ ] styling the page #32
