### ISSUE TITLE
Blog Article

### ISSUE THREAD

**Issue by Salam-Dalloul** [facg3/Elegant-Project#6]
#1 
as a user i want to show more information about topics that i want to read about

**Acceptance Criteria** 

- [ ] show the article details from database #23 
- [ ] update the liked table if user press like #30
- [ ] styling the page #31
