### ISSUE TITLE
Contact us

### ISSUE THREAD

**Issue by Salam-Dalloul** [facg3/Elegant-Project#9]
#1
as a user i want to contact the website owners 

**Acceptance Criteria**

- [ ] display the contact us form #35
- [ ] take the information and send them to the back end #39 
- [ ] send information from back end to the admin's email #39 
- [ ] styling the page #40
